package org.jrecruiter.model;

// Generated Dec 25, 2006 9:26:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "configuration", uniqueConstraints = {})
public class Configuration implements java.io.Serializable {

	// Fields    

	private String messageKey;

	private String messageText;

	private Date lastModified;

	// Constructors

	/** default constructor */
	public Configuration() {
	}

	/** minimal constructor */
	public Configuration(String messageKey) {
		this.messageKey = messageKey;
	}

	/** full constructor */
	public Configuration(String messageKey, String messageText,
			Date lastModified) {
		this.messageKey = messageKey;
		this.messageText = messageText;
		this.lastModified = lastModified;
	}

	// Property accessors
	@Id
	@Column(name = "message_key", unique = true, nullable = false, insertable = true, updatable = true, length = 0)
	public String getMessageKey() {
		return this.messageKey;
	}

	public void setMessageKey(String messageKey) {
		this.messageKey = messageKey;
	}

	@Column(name = "message_text", unique = false, nullable = true, insertable = true, updatable = true)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "last_modified", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
