package org.jrecruiter.model;

// Generated Dec 25, 2006 9:26:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "jobs", uniqueConstraints = {})
public class Jobs implements java.io.Serializable {

	// Fields    

	private int jobId;

	private String businessName;

	private String businessLocation;

	private String jobTitle;

	private Long salary;

	private String description;

	private String webSite;

	private String businessAddress1;

	private String businessAddress2;

	private String businessCity;

	private String businessState;

	private String businessZip;

	private String businessPhone;

	private String businessEmail;

	private String industry;

	private String jobRestrictions;

	private Date registerDate;

	private Date expireDate;

	private Date updateDate;

	private int status;

	private String userName;

	private Set<Statistics> statisticses = new HashSet<Statistics>(0);

	// Constructors

	/** default constructor */
	public Jobs() {
	}

	/** minimal constructor */
	public Jobs(int jobId, String businessName, String jobTitle,
			String description, int status) {
		this.jobId = jobId;
		this.businessName = businessName;
		this.jobTitle = jobTitle;
		this.description = description;
		this.status = status;
	}

	/** full constructor */
	public Jobs(int jobId, String businessName, String businessLocation,
			String jobTitle, Long salary, String description, String webSite,
			String businessAddress1, String businessAddress2,
			String businessCity, String businessState, String businessZip,
			String businessPhone, String businessEmail, String industry,
			String jobRestrictions, Date registerDate, Date expireDate,
			Date updateDate, int status, String userName,
			Set<Statistics> statisticses) {
		this.jobId = jobId;
		this.businessName = businessName;
		this.businessLocation = businessLocation;
		this.jobTitle = jobTitle;
		this.salary = salary;
		this.description = description;
		this.webSite = webSite;
		this.businessAddress1 = businessAddress1;
		this.businessAddress2 = businessAddress2;
		this.businessCity = businessCity;
		this.businessState = businessState;
		this.businessZip = businessZip;
		this.businessPhone = businessPhone;
		this.businessEmail = businessEmail;
		this.industry = industry;
		this.jobRestrictions = jobRestrictions;
		this.registerDate = registerDate;
		this.expireDate = expireDate;
		this.updateDate = updateDate;
		this.status = status;
		this.userName = userName;
		this.statisticses = statisticses;
	}

	// Property accessors
	@Id
	@Column(name = "job_id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	@Column(name = "business_name", unique = false, nullable = false, insertable = true, updatable = true, length = 100)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@Column(name = "business_location", unique = false, nullable = true, insertable = true, updatable = true, length = 100)
	public String getBusinessLocation() {
		return this.businessLocation;
	}

	public void setBusinessLocation(String businessLocation) {
		this.businessLocation = businessLocation;
	}

	@Column(name = "job_title", unique = false, nullable = false, insertable = true, updatable = true, length = 100)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "salary", unique = false, nullable = true, insertable = true, updatable = true, precision = 18, scale = 0)
	public Long getSalary() {
		return this.salary;
	}

	public void setSalary(Long salary) {
		this.salary = salary;
	}

	@Column(name = "description", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "web_site", unique = false, nullable = true, insertable = true, updatable = true, length = 100)
	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	@Column(name = "business_address1", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public String getBusinessAddress1() {
		return this.businessAddress1;
	}

	public void setBusinessAddress1(String businessAddress1) {
		this.businessAddress1 = businessAddress1;
	}

	@Column(name = "business_address2", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public String getBusinessAddress2() {
		return this.businessAddress2;
	}

	public void setBusinessAddress2(String businessAddress2) {
		this.businessAddress2 = businessAddress2;
	}

	@Column(name = "business_city", unique = false, nullable = true, insertable = true, updatable = true, length = 30)
	public String getBusinessCity() {
		return this.businessCity;
	}

	public void setBusinessCity(String businessCity) {
		this.businessCity = businessCity;
	}

	@Column(name = "business_state", unique = false, nullable = true, insertable = true, updatable = true, length = 20)
	public String getBusinessState() {
		return this.businessState;
	}

	public void setBusinessState(String businessState) {
		this.businessState = businessState;
	}

	@Column(name = "business_zip", unique = false, nullable = true, insertable = true, updatable = true, length = 15)
	public String getBusinessZip() {
		return this.businessZip;
	}

	public void setBusinessZip(String businessZip) {
		this.businessZip = businessZip;
	}

	@Column(name = "business_phone", unique = false, nullable = true, insertable = true, updatable = true, length = 15)
	public String getBusinessPhone() {
		return this.businessPhone;
	}

	public void setBusinessPhone(String businessPhone) {
		this.businessPhone = businessPhone;
	}

	@Column(name = "business_email", unique = false, nullable = true, insertable = true, updatable = true, length = 200)
	public String getBusinessEmail() {
		return this.businessEmail;
	}

	public void setBusinessEmail(String businessEmail) {
		this.businessEmail = businessEmail;
	}

	@Column(name = "industry", unique = false, nullable = true, insertable = true, updatable = true, length = 30)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "job_restrictions", unique = false, nullable = true, insertable = true, updatable = true, length = 0)
	public String getJobRestrictions() {
		return this.jobRestrictions;
	}

	public void setJobRestrictions(String jobRestrictions) {
		this.jobRestrictions = jobRestrictions;
	}

	@Column(name = "register_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "expire_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "update_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "user_name", unique = false, nullable = true, insertable = true, updatable = true, length = 25)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<Statistics> getStatisticses() {
		return this.statisticses;
	}

	public void setStatisticses(Set<Statistics> statisticses) {
		this.statisticses = statisticses;
	}

}
