package org.jrecruiter.model;

// Generated Dec 25, 2006 9:26:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", uniqueConstraints = {})
public class Roles implements java.io.Serializable {

	// Fields    

	private String name;

	private String description;

	private Set<Users> userses = new HashSet<Users>(0);

	// Constructors

	/** default constructor */
	public Roles() {
	}

	/** minimal constructor */
	public Roles(String name) {
		this.name = name;
	}

	/** full constructor */
	public Roles(String name, String description, Set<Users> userses) {
		this.name = name;
		this.description = description;
		this.userses = userses;
	}

	// Property accessors
	@Id
	@Column(name = "name", unique = true, nullable = false, insertable = true, updatable = true, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", unique = false, nullable = true, insertable = true, updatable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "roleses")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
