package org.jrecruiter.model;

// Generated Dec 25, 2006 9:26:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = {})
public class Users implements java.io.Serializable {

	// Fields    

	private String userName;

	private String userPasswd;

	private String firstName;

	private String lastName;

	private String phone;

	private String fax;

	private String email;

	private Date registerDate;

	private Date expireDate;

	private Date updateDate;

	private String company;

	private Set<Roles> roleses = new HashSet<Roles>(0);

	// Constructors

	/** default constructor */
	public Users() {
	}

	/** minimal constructor */
	public Users(String userName, String userPasswd) {
		this.userName = userName;
		this.userPasswd = userPasswd;
	}

	/** full constructor */
	public Users(String userName, String userPasswd, String firstName,
			String lastName, String phone, String fax, String email,
			Date registerDate, Date expireDate, Date updateDate,
			String company, Set<Roles> roleses) {
		this.userName = userName;
		this.userPasswd = userPasswd;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.registerDate = registerDate;
		this.expireDate = expireDate;
		this.updateDate = updateDate;
		this.company = company;
		this.roleses = roleses;
	}

	// Property accessors
	@Id
	@Column(name = "user_name", unique = true, nullable = false, insertable = true, updatable = true, length = 25)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_passwd", unique = false, nullable = false, insertable = true, updatable = true, length = 25)
	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	@Column(name = "first_name", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phone", unique = false, nullable = true, insertable = true, updatable = true, length = 25)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax", unique = false, nullable = true, insertable = true, updatable = true, length = 25)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "register_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "expire_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "update_date", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "company", unique = false, nullable = true, insertable = true, updatable = true, length = 25)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@ManyToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "userses")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
